---
apiVersion: v1
kind: Service
metadata:
  name: ctfd
  namespace: ctfd
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: ctfd
spec:
  selector:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: ctfd
  ports:
    - name: http
      port: 80
      targetPort: http
