---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: ctfd
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: mariadb
type: Opaque
stringData:
  MARIADB_RANDOM_ROOT_PASSWORD: "yes"
  MARIADB_USER: "ctfd"
  MARIADB_PASSWORD: "ctfd"
  MARIADB_DATABASE: "ctfd"
  MARIADB_AUTO_UPGRADE: "yes"
