---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: ctfd
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ctfd
      app.kubernetes.io/component: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ctfd
        app.kubernetes.io/component: mariadb
    spec:
      serviceAccountName: mariadb
      securityContext:
        runAsUser: 999 # mysql
        runAsNonRoot: true
      containers:
        - name: mariadb
          image: mariadb:11.7.2
          args:
            - --pid-file=/tmp/mysqld.pid
            - --socket=/tmp/mysqld.sock
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: mariadb
              containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /tmp
              name: tmp
          resources:
            requests:
              memory: 3Gi
              cpu: 100m
            limits:
              memory: 4Gi
          startupProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
          readinessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
          livenessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
