---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: ctfd
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: mariadb
automountServiceAccountToken: false
