---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: ctfd
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: redis
automountServiceAccountToken: false
