---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ctfd
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ctfd
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ctfd
        app.kubernetes.io/component: redis
    spec:
      serviceAccountName: redis
      securityContext:
        runAsUser: 999 # redis
        runAsNonRoot: true
      containers:
        - name: redis
          image: redis:7.4.2
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: tmp
          resources:
            requests:
              memory: 3Gi
              cpu: 100m
            limits:
              memory: 4Gi
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
