---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ctfd
  labels:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: redis
spec:
  selector:
    app.kubernetes.io/name: ctfd
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
