---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctf-ui-operator-deny-all
  namespace: ctf-ui-operator
  labels:
    app.kubernetes.io/name: ctf-ui-operator
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctf-ui-operator-allow-namespace-egress
  namespace: ctf-ui-operator
  labels:
    app.kubernetes.io/name: ctf-ui-operator
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
