---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-ui-operator
  namespace: ctf-ui-operator
  labels:
    app.kubernetes.io/name: ctf-ui-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ctf-ui-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ctf-ui-operator
    spec:
      serviceAccountName: ctf-ui-operator
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: manager
          image: backbone81/ctf-ui-operator:local
          command:
            - /ctf-ui-operator
          args:
            - --metrics-bind-address=:3000
            - --health-probe-bind-address=:3001
            - --leader-election-enabled
            - --leader-election-namespace=$(POD_NAMESPACE)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /readyz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          ports:
            - name: metrics
              containerPort: 3000
            - name: health
              containerPort: 3001
