---
apiVersion: ui.ctf.backbone81/v1alpha1
kind: CTFd
metadata:
  name: ctfd-sample
spec:
  title: Demo CTF
  description: This is a demo CTF.
  userMode: teams
  challengeVisibility: private
  accountVisibility: private
  scoreVisibility: private
  registrationVisibility: private
  verifyEmails: true
  teamSize: 5
  theme: core-beta
  themeColor:
  start:
  end:
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 2Gi
  redis:
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 2Gi
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  mariaDb:
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 2Gi
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  minio:
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 2Gi
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

