---
apiVersion: ui.ctf.backbone81/v1alpha1
kind: CTFd
metadata:
  name: ctfd-sample
spec:
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 2Gi
  redis:
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 2Gi
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  mariaDB:
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 2Gi
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  minio:
    resources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 2Gi
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

