---
apiVersion: ui.ctf.backbone81/v1alpha1
kind: Redis
metadata:
  name: redis-sample
spec:
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 2Gi
  persistentVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
