apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ctf-ui-operator
  name: ctf-ui-operator
  namespace: ctf-ui-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ctf-ui-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ctf-ui-operator
    spec:
      containers:
      - args:
        - --metrics-bind-address=:3000
        - --health-probe-bind-address=:3001
        - --leader-election-enabled
        - --leader-election-namespace=$(POD_NAMESPACE)
        command:
        - /ctf-ui-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: backbone81/ctf-ui-operator:local
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        name: manager
        ports:
        - containerPort: 3000
          name: metrics
        - containerPort: 3001
          name: health
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        startupProbe:
          httpGet:
            path: /readyz
            port: health
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: ctf-ui-operator
