apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: ctf-ui-operator
  name: ctf-ui-operator-deny-all
  namespace: ctf-ui-operator
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
