apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: ctf-ui-operator
  name: ctf-ui-operator-allow-namespace-egress
  namespace: ctf-ui-operator
spec:
  egress:
  - to:
    - namespaceSelector: {}
  podSelector: {}
  policyTypes:
  - Egress
