apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ctf-ui-operator
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ui.ctf.backbone81
  resources:
  - ctfds
  - mariadbs
  - minios
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ui.ctf.backbone81
  resources:
  - ctfds/finalizers
  - mariadbs/finalizers
  - minios/finalizers
  - redis/finalizers
  verbs:
  - update
- apiGroups:
  - ui.ctf.backbone81
  resources:
  - ctfds/status
  - mariadbs/status
  - minios/status
  - redis/status
  verbs:
  - get
  - patch
  - update
