apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ctf-ui-operator
  name: ctf-ui-operator
  namespace: ctf-ui-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctf-ui-operator
subjects:
- kind: ServiceAccount
  name: ctf-ui-operator
  namespace: ctf-ui-operator
